title: Razvan Creanga
author: Razvan Creanga
avatar: /assets/img/Razvan_photo.jpeg
description: >- # this means to ignore newlines until "baseurl:"
  Entrepreneur and sports lover.
baseurl: /
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://razvancreanga.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-129795094-1
paginate: 5
paginate_path: "/blog/:num/"

permalink: pretty

# Build settings
#theme: jekyll-theme-hamilton
skin: daylight
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
#  - jekyll-feed
remote_theme: ngzhio/jekyll-theme-hamilton

#twitter:
#  username: rcreanga
#  card: summary

social:
  name: Razvan Creanga
  links:
    - https://x.com/rcreanga