title: Razvan Creanga
author: Razvan Creanga
avatar: /assets/img/Razvan_photo.jpeg
description: >- # this means to ignore newlines until "baseurl:"
  Entrepreneur. Forbes 30 under 30. Passionate about high-impact initiatives with strong and meaningful missions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://razvancreanga.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-129795094-1
paginate: 5
paginate_path: "/blog/:num/"
host: https://razvancreanga.com

permalink: pretty

# Build settings
theme: jekyll-theme-hamilton
skin: daylight
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-feed

twitter:
  username: rcreanga
  card: summary

social:
  name: Razvan Creanga
  links:
    - https://twitter.com/rcreanga
    - https://www.facebook.com/razcreanga
    - https://linkedin.com/in/rcreanga
